site_name: Nertivia-Compose docs
site_description: 'Documentation for Nertivia-Compose'
site_author: 'Cyber'
docs_dir: docs/
repo_url: 'https://github.com/Nertivia-Compose/instance'
edit_uri: 'https://github.com/Nertivia-Compose/docs/edit/main/docs'
nav:
    - Home: index.md
    - Requirements: requirements.md
    - "Explanations":
      - "docker-compose.yml": explanations/docker-compose-file.md
      - ".env file": explanations/env-file.md
      - ".utils.sh": explanations/utils-file.md
    - "Setup":
      - "Local machinne": setup/localhost.md
      - "Play with Docker": setup/pwd.md
    - "Database connection":
      - database-connection/linux.md
      - database-connection/windows.md
theme:
  name: 'material'
markdown_extensions:
  - admonition
  - mdx_truly_sane_lists
  - attr_list